version: "3.8"

services:
  app:
    container_name: campaign-service
    image: campaign-service
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 4000:4000